spring:
  datasource:
    url: jdbc:mariadb://${DBHOST}:${DBPORT}/${DBDATABASE}
    username: ${DBUSER}
    password: ${DBPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create